// Auto-generated module declarations
// DO NOT EDIT MANUALLY
#![allow(unused)]

use crate::lexer::PtxToken;
use crate::unparser::PtxUnparser;
use crate::r#type::instruction::Inst;

pub mod abs;
pub mod activemask;
pub mod add_cc;
pub mod add;
pub mod addc;
pub mod alloca;
pub mod and;
pub mod applypriority;
pub mod atom;
pub mod bar;
pub mod bar_warp_sync;
pub mod barrier_cluster;
pub mod bfe;
pub mod bfi;
pub mod bfind;
pub mod bmsk;
pub mod bra;
pub mod brev;
pub mod brkpt;
pub mod brx_idx;
pub mod call;
pub mod clusterlaunchcontrol_query_cancel;
pub mod clusterlaunchcontrol_try_cancel;
pub mod clz;
pub mod cnot;
pub mod copysign;
pub mod cos;
pub mod cp_async_bulk_commit_group;
pub mod cp_async_bulk_prefetch_tensor;
pub mod cp_async_bulk_prefetch;
pub mod cp_async_bulk_tensor;
pub mod cp_async_bulk;
pub mod cp_async_bulk_wait_group;
pub mod cp_async_commit_group;
pub mod cp_async_mbarrier_arrive;
pub mod cp_async;
pub mod cp_async_wait_group;
pub mod cp_reduce_async_bulk_tensor;
pub mod cp_reduce_async_bulk;
pub mod createpolicy;
pub mod cvt_pack;
pub mod cvt;
pub mod cvta;
pub mod discard;
pub mod div;
pub mod dp2a;
pub mod dp4a;
pub mod elect_sync;
pub mod ex2;
pub mod exit;
pub mod fma;
pub mod fns;
pub mod getctarank;
pub mod griddepcontrol;
pub mod isspacep;
pub mod istypep;
pub mod ld_global_nc;
pub mod ld;
pub mod ldmatrix;
pub mod ldu;
pub mod lg2;
pub mod lop3;
pub mod mad_cc;
pub mod mad;
pub mod mad24;
pub mod madc;
pub mod mapa;
pub mod match_sync;
pub mod max;
pub mod mbarrier_arrive;
pub mod mbarrier_arrive_drop;
pub mod mbarrier_complete_tx;
pub mod mbarrier_expect_tx;
pub mod mbarrier_init;
pub mod mbarrier_inval;
pub mod mbarrier_pending_count;
pub mod mbarrier_test_wait;
pub mod membar;
pub mod min;
pub mod mma_sp;
pub mod mma;
pub mod mov;
pub mod movmatrix;
pub mod mul;
pub mod mul24;
pub mod multimem_ld_reduce;
pub mod nanosleep;
pub mod neg;
pub mod not;
pub mod or;
pub mod pmevent;
pub mod popc;
pub mod prefetch;
pub mod prmt;
pub mod rcp_approx_ftz_f64;
pub mod rcp;
pub mod red_async;
pub mod red;
pub mod redux_sync;
pub mod rem;
pub mod ret;
pub mod rsqrt_approx_ftz_f64;
pub mod rsqrt;
pub mod sad;
pub mod selp;
pub mod set;
pub mod setmaxnreg;
pub mod setp;
pub mod shf;
pub mod shfl_sync;
pub mod shfl;
pub mod shl;
pub mod shr;
pub mod sin;
pub mod slct;
pub mod sqrt;
pub mod st_async;
pub mod st_bulk;
pub mod st;
pub mod stackrestore;
pub mod stacksave;
pub mod stmatrix;
pub mod sub_cc;
pub mod sub;
pub mod subc;
pub mod suld;
pub mod suq;
pub mod sured;
pub mod sust;
pub mod szext;
pub mod tanh;
pub mod tcgen05_alloc;
pub mod tcgen05_commit;
pub mod tcgen05_cp;
pub mod tcgen05_fence;
pub mod tcgen05_ld;
pub mod tcgen05_mma_sp;
pub mod tcgen05_mma;
pub mod tcgen05_mma_ws_sp;
pub mod tcgen05_mma_ws;
pub mod tcgen05_shift;
pub mod tcgen05_st;
pub mod tcgen05_wait;
pub mod tensormap_cp_fenceproxy;
pub mod tensormap_replace;
pub mod testp;
pub mod tex;
pub mod tld4;
pub mod trap;
pub mod txq;
pub mod vmad;
pub mod vop;
pub mod vop2;
pub mod vop4;
pub mod vote_sync;
pub mod vote;
pub mod vset;
pub mod vset2;
pub mod vset4;
pub mod vsh;
pub mod wgmma_commit_group;
pub mod wgmma_fence;
pub mod wgmma_mma_async_sp;
pub mod wgmma_mma_async;
pub mod wgmma_wait_group;
pub mod wmma_load;
pub mod wmma_mma;
pub mod wmma_store;
pub mod xor;

impl PtxUnparser for Inst {
    fn unparse_tokens(&self, tokens: &mut Vec<PtxToken>) {
        match self {
            Inst::AbsType(value) => value.unparse_tokens(tokens),
            Inst::AbsFtzF32(value) => value.unparse_tokens(tokens),
            Inst::AbsF64(value) => value.unparse_tokens(tokens),
            Inst::AbsFtzF16(value) => value.unparse_tokens(tokens),
            Inst::AbsFtzF16x2(value) => value.unparse_tokens(tokens),
            Inst::AbsBf16(value) => value.unparse_tokens(tokens),
            Inst::AbsBf16x2(value) => value.unparse_tokens(tokens),
            Inst::ActivemaskB32(value) => value.unparse_tokens(tokens),
            Inst::AddCcType(value) => value.unparse_tokens(tokens),
            Inst::AddType(value) => value.unparse_tokens(tokens),
            Inst::AddSatS32(value) => value.unparse_tokens(tokens),
            Inst::AddRndFtzSatF32(value) => value.unparse_tokens(tokens),
            Inst::AddRndFtzF32x2(value) => value.unparse_tokens(tokens),
            Inst::AddRndF64(value) => value.unparse_tokens(tokens),
            Inst::AddRndFtzSatF16(value) => value.unparse_tokens(tokens),
            Inst::AddRndFtzSatF16x2(value) => value.unparse_tokens(tokens),
            Inst::AddRndBf16(value) => value.unparse_tokens(tokens),
            Inst::AddRndBf16x2(value) => value.unparse_tokens(tokens),
            Inst::AddRndSatF32Atype(value) => value.unparse_tokens(tokens),
            Inst::AddcCcType(value) => value.unparse_tokens(tokens),
            Inst::AllocaType(value) => value.unparse_tokens(tokens),
            Inst::AndType(value) => value.unparse_tokens(tokens),
            Inst::ApplypriorityGlobalLevelEvictionPriority(value) => value.unparse_tokens(tokens),
            Inst::AtomSemScopeSpaceOpLevelCacheHintType(value) => value.unparse_tokens(tokens),
            Inst::AtomSemScopeSpaceOpType(value) => value.unparse_tokens(tokens),
            Inst::AtomSemScopeSpaceCasB16(value) => value.unparse_tokens(tokens),
            Inst::AtomSemScopeSpaceCasB128(value) => value.unparse_tokens(tokens),
            Inst::AtomSemScopeSpaceExchLevelCacheHintB128(value) => value.unparse_tokens(tokens),
            Inst::AtomSemScopeSpaceAddNoftzLevelCacheHintF16(value) => value.unparse_tokens(tokens),
            Inst::AtomSemScopeSpaceAddNoftzLevelCacheHintF16x2(value) => value.unparse_tokens(tokens),
            Inst::AtomSemScopeSpaceAddNoftzLevelCacheHintBf16(value) => value.unparse_tokens(tokens),
            Inst::AtomSemScopeSpaceAddNoftzLevelCacheHintBf16x2(value) => value.unparse_tokens(tokens),
            Inst::AtomSemScopeGlobalAddLevelCacheHintVec32BitF32(value) => value.unparse_tokens(tokens),
            Inst::AtomSemScopeGlobalOpNoftzLevelCacheHintVec16BitHalfWordType(value) => value.unparse_tokens(tokens),
            Inst::AtomSemScopeGlobalOpNoftzLevelCacheHintVec32BitPackedType(value) => value.unparse_tokens(tokens),
            Inst::BarrierCtaSyncAligned(value) => value.unparse_tokens(tokens),
            Inst::BarrierCtaArriveAligned(value) => value.unparse_tokens(tokens),
            Inst::BarrierCtaRedPopcAlignedU32(value) => value.unparse_tokens(tokens),
            Inst::BarrierCtaRedOpAlignedPred(value) => value.unparse_tokens(tokens),
            Inst::BarCtaSync(value) => value.unparse_tokens(tokens),
            Inst::BarCtaArrive(value) => value.unparse_tokens(tokens),
            Inst::BarCtaRedPopcU32(value) => value.unparse_tokens(tokens),
            Inst::BarCtaRedOpPred(value) => value.unparse_tokens(tokens),
            Inst::BarWarpSync(value) => value.unparse_tokens(tokens),
            Inst::BarrierClusterArriveSemAligned(value) => value.unparse_tokens(tokens),
            Inst::BarrierClusterWaitAcquireAligned(value) => value.unparse_tokens(tokens),
            Inst::BfeType(value) => value.unparse_tokens(tokens),
            Inst::BfiType(value) => value.unparse_tokens(tokens),
            Inst::BfindType(value) => value.unparse_tokens(tokens),
            Inst::BfindShiftamtType(value) => value.unparse_tokens(tokens),
            Inst::BmskModeB32(value) => value.unparse_tokens(tokens),
            Inst::BraUni(value) => value.unparse_tokens(tokens),
            Inst::BraUni1(value) => value.unparse_tokens(tokens),
            Inst::BrevType(value) => value.unparse_tokens(tokens),
            Inst::Brkpt(value) => value.unparse_tokens(tokens),
            Inst::BrxIdxUni(value) => value.unparse_tokens(tokens),
            Inst::BrxIdxUni1(value) => value.unparse_tokens(tokens),
            Inst::CallUni(value) => value.unparse_tokens(tokens),
            Inst::CallUni1(value) => value.unparse_tokens(tokens),
            Inst::CallUni2(value) => value.unparse_tokens(tokens),
            Inst::CallUni3(value) => value.unparse_tokens(tokens),
            Inst::CallUni4(value) => value.unparse_tokens(tokens),
            Inst::CallUni5(value) => value.unparse_tokens(tokens),
            Inst::CallUni6(value) => value.unparse_tokens(tokens),
            Inst::CallUni7(value) => value.unparse_tokens(tokens),
            Inst::CallUni8(value) => value.unparse_tokens(tokens),
            Inst::ClusterlaunchcontrolQueryCancelIsCanceledPredB128(value) => value.unparse_tokens(tokens),
            Inst::ClusterlaunchcontrolQueryCancelGetFirstCtaidV4B32B128(value) => value.unparse_tokens(tokens),
            Inst::ClusterlaunchcontrolQueryCancelGetFirstCtaidDimensionB32B128(value) => value.unparse_tokens(tokens),
            Inst::ClusterlaunchcontrolTryCancelAsyncSpaceCompletionMechanismMulticastClusterAllB128(value) => value.unparse_tokens(tokens),
            Inst::ClzType(value) => value.unparse_tokens(tokens),
            Inst::CnotType(value) => value.unparse_tokens(tokens),
            Inst::CopysignType(value) => value.unparse_tokens(tokens),
            Inst::CosApproxFtzF32(value) => value.unparse_tokens(tokens),
            Inst::CpAsyncBulkCommitGroup(value) => value.unparse_tokens(tokens),
            Inst::CpAsyncBulkPrefetchTensorDimL2SrcLoadModeLevelCacheHint(value) => value.unparse_tokens(tokens),
            Inst::CpAsyncBulkPrefetchL2SrcLevelCacheHint(value) => value.unparse_tokens(tokens),
            Inst::CpAsyncBulkTensorDimDstSrcLoadModeCompletionMechanismCtaGroupLevelCacheHint(value) => value.unparse_tokens(tokens),
            Inst::CpAsyncBulkTensorDimDstSrcLoadModeCompletionMechanismMulticastCtaGroupLevelCacheHint(value) => value.unparse_tokens(tokens),
            Inst::CpAsyncBulkTensorDimDstSrcLoadModeCompletionMechanismLevelCacheHint(value) => value.unparse_tokens(tokens),
            Inst::CpAsyncBulkDstSrcCompletionMechanismLevelCacheHint(value) => value.unparse_tokens(tokens),
            Inst::CpAsyncBulkDstSrcCompletionMechanismMulticastLevelCacheHint(value) => value.unparse_tokens(tokens),
            Inst::CpAsyncBulkDstSrcCompletionMechanism(value) => value.unparse_tokens(tokens),
            Inst::CpAsyncBulkDstSrcCompletionMechanismLevelCacheHintCpMask(value) => value.unparse_tokens(tokens),
            Inst::CpAsyncBulkWaitGroupRead(value) => value.unparse_tokens(tokens),
            Inst::CpAsyncCommitGroup(value) => value.unparse_tokens(tokens),
            Inst::CpAsyncMbarrierArriveNoincStateB64(value) => value.unparse_tokens(tokens),
            Inst::CpAsyncCaStateGlobalLevelCacheHintLevelPrefetchSize(value) => value.unparse_tokens(tokens),
            Inst::CpAsyncCgStateGlobalLevelCacheHintLevelPrefetchSize(value) => value.unparse_tokens(tokens),
            Inst::CpAsyncCaStateGlobalLevelCacheHintLevelPrefetchSize1(value) => value.unparse_tokens(tokens),
            Inst::CpAsyncCgStateGlobalLevelCacheHintLevelPrefetchSize1(value) => value.unparse_tokens(tokens),
            Inst::CpAsyncWaitGroup(value) => value.unparse_tokens(tokens),
            Inst::CpAsyncWaitAll(value) => value.unparse_tokens(tokens),
            Inst::CpReduceAsyncBulkTensorDimDstSrcRedopLoadModeCompletionMechanismLevelCacheHint(value) => value.unparse_tokens(tokens),
            Inst::CpReduceAsyncBulkDstSrcCompletionMechanismRedopType(value) => value.unparse_tokens(tokens),
            Inst::CpReduceAsyncBulkDstSrcCompletionMechanismLevelCacheHintRedopType(value) => value.unparse_tokens(tokens),
            Inst::CpReduceAsyncBulkDstSrcCompletionMechanismLevelCacheHintAddNoftzType(value) => value.unparse_tokens(tokens),
            Inst::CreatepolicyRangeGlobalLevelPrimaryPriorityLevelSecondaryPriorityB64(value) => value.unparse_tokens(tokens),
            Inst::CreatepolicyFractionalLevelPrimaryPriorityLevelSecondaryPriorityB64(value) => value.unparse_tokens(tokens),
            Inst::CreatepolicyCvtL2B64(value) => value.unparse_tokens(tokens),
            Inst::CvtPackSatConverttypeAbtype(value) => value.unparse_tokens(tokens),
            Inst::CvtPackSatConverttypeAbtypeCtype(value) => value.unparse_tokens(tokens),
            Inst::CvtIrndFtzSatDtypeAtype(value) => value.unparse_tokens(tokens),
            Inst::CvtFrndFtzSatDtypeAtype(value) => value.unparse_tokens(tokens),
            Inst::CvtFrnd2ReluSatfiniteF16F32(value) => value.unparse_tokens(tokens),
            Inst::CvtFrnd2ReluSatfiniteF16x2F32(value) => value.unparse_tokens(tokens),
            Inst::CvtRsReluSatfiniteF16x2F32(value) => value.unparse_tokens(tokens),
            Inst::CvtFrnd2ReluSatfiniteBf16F32(value) => value.unparse_tokens(tokens),
            Inst::CvtFrnd2ReluSatfiniteBf16x2F32(value) => value.unparse_tokens(tokens),
            Inst::CvtRsReluSatfiniteBf16x2F32(value) => value.unparse_tokens(tokens),
            Inst::CvtRnaSatfiniteTf32F32(value) => value.unparse_tokens(tokens),
            Inst::CvtFrnd2SatfiniteReluTf32F32(value) => value.unparse_tokens(tokens),
            Inst::CvtRnSatfiniteReluF8x2typeF32(value) => value.unparse_tokens(tokens),
            Inst::CvtRnSatfiniteReluF8x2typeF16x2(value) => value.unparse_tokens(tokens),
            Inst::CvtRnReluF16x2F8x2type(value) => value.unparse_tokens(tokens),
            Inst::CvtRsReluSatfiniteF8x4typeF32(value) => value.unparse_tokens(tokens),
            Inst::CvtRnSatfiniteReluF4x2typeF32(value) => value.unparse_tokens(tokens),
            Inst::CvtRnReluF16x2F4x2type(value) => value.unparse_tokens(tokens),
            Inst::CvtRsReluSatfiniteF4x4typeF32(value) => value.unparse_tokens(tokens),
            Inst::CvtRnSatfiniteReluF6x2typeF32(value) => value.unparse_tokens(tokens),
            Inst::CvtRnReluF16x2F6x2type(value) => value.unparse_tokens(tokens),
            Inst::CvtRsReluSatfiniteF6x4typeF32(value) => value.unparse_tokens(tokens),
            Inst::CvtFrnd3SatfiniteUe8m0x2F32(value) => value.unparse_tokens(tokens),
            Inst::CvtFrnd3SatfiniteUe8m0x2Bf16x2(value) => value.unparse_tokens(tokens),
            Inst::CvtRnBf16x2Ue8m0x2(value) => value.unparse_tokens(tokens),
            Inst::CvtaSpaceSize(value) => value.unparse_tokens(tokens),
            Inst::CvtaToSpaceSize(value) => value.unparse_tokens(tokens),
            Inst::DiscardGlobalLevel(value) => value.unparse_tokens(tokens),
            Inst::DivType(value) => value.unparse_tokens(tokens),
            Inst::DivApproxFtzF32(value) => value.unparse_tokens(tokens),
            Inst::DivFullFtzF32(value) => value.unparse_tokens(tokens),
            Inst::DivRndFtzF32(value) => value.unparse_tokens(tokens),
            Inst::DivRndF64(value) => value.unparse_tokens(tokens),
            Inst::Dp2aModeAtypeBtype(value) => value.unparse_tokens(tokens),
            Inst::Dp4aAtypeBtype(value) => value.unparse_tokens(tokens),
            Inst::ElectSync(value) => value.unparse_tokens(tokens),
            Inst::Ex2ApproxFtzF32(value) => value.unparse_tokens(tokens),
            Inst::Ex2ApproxAtype(value) => value.unparse_tokens(tokens),
            Inst::Ex2ApproxFtzBtype(value) => value.unparse_tokens(tokens),
            Inst::Exit(value) => value.unparse_tokens(tokens),
            Inst::FmaRndFtzSatF32(value) => value.unparse_tokens(tokens),
            Inst::FmaRndFtzF32x2(value) => value.unparse_tokens(tokens),
            Inst::FmaRndF64(value) => value.unparse_tokens(tokens),
            Inst::FmaRndFtzSatF16(value) => value.unparse_tokens(tokens),
            Inst::FmaRndFtzSatF16x2(value) => value.unparse_tokens(tokens),
            Inst::FmaRndFtzReluF16(value) => value.unparse_tokens(tokens),
            Inst::FmaRndFtzReluF16x2(value) => value.unparse_tokens(tokens),
            Inst::FmaRndReluBf16(value) => value.unparse_tokens(tokens),
            Inst::FmaRndReluBf16x2(value) => value.unparse_tokens(tokens),
            Inst::FmaRndOobReluType(value) => value.unparse_tokens(tokens),
            Inst::FmaRndSatF32Abtype(value) => value.unparse_tokens(tokens),
            Inst::FnsB32(value) => value.unparse_tokens(tokens),
            Inst::GetctarankSpaceType(value) => value.unparse_tokens(tokens),
            Inst::GetctarankSharedClusterType(value) => value.unparse_tokens(tokens),
            Inst::GetctarankType(value) => value.unparse_tokens(tokens),
            Inst::GriddepcontrolAction(value) => value.unparse_tokens(tokens),
            Inst::IsspacepSpace(value) => value.unparse_tokens(tokens),
            Inst::IstypepType(value) => value.unparse_tokens(tokens),
            Inst::LdGlobalCopNcLevelCacheHintLevelPrefetchSizeType(value) => value.unparse_tokens(tokens),
            Inst::LdGlobalCopNcLevelCacheHintLevelPrefetchSizeVecType(value) => value.unparse_tokens(tokens),
            Inst::LdGlobalNcLevel1EvictionPriorityLevel2EvictionPriorityLevelCacheHintLevelPrefetchSizeType(value) => value.unparse_tokens(tokens),
            Inst::LdGlobalNcLevel1EvictionPriorityLevel2EvictionPriorityLevelCacheHintLevelPrefetchSizeVecType(value) => value.unparse_tokens(tokens),
            Inst::LdWeakSsCopLevelCacheHintLevelPrefetchSizeVecType(value) => value.unparse_tokens(tokens),
            Inst::LdWeakSsLevel1EvictionPriorityLevel2EvictionPriorityLevelCacheHintLevelPrefetchSizeVecType(value) => value.unparse_tokens(tokens),
            Inst::LdVolatileSsLevelPrefetchSizeVecType(value) => value.unparse_tokens(tokens),
            Inst::LdRelaxedScopeSsLevel1EvictionPriorityLevel2EvictionPriorityLevelCacheHintLevelPrefetchSizeVecType(value) => value.unparse_tokens(tokens),
            Inst::LdAcquireScopeSsLevel1EvictionPriorityLevel2EvictionPriorityLevelCacheHintLevelPrefetchSizeVecType(value) => value.unparse_tokens(tokens),
            Inst::LdMmioRelaxedSysGlobalType(value) => value.unparse_tokens(tokens),
            Inst::LdmatrixSyncAlignedShapeNumTransSsType(value) => value.unparse_tokens(tokens),
            Inst::LdmatrixSyncAlignedM8n16NumSsDstFmtSrcFmt(value) => value.unparse_tokens(tokens),
            Inst::LdmatrixSyncAlignedM16n16NumTransSsDstFmtSrcFmt(value) => value.unparse_tokens(tokens),
            Inst::LduSsType(value) => value.unparse_tokens(tokens),
            Inst::LduSsVecType(value) => value.unparse_tokens(tokens),
            Inst::Lg2ApproxFtzF32(value) => value.unparse_tokens(tokens),
            Inst::Lop3B32(value) => value.unparse_tokens(tokens),
            Inst::Lop3BoolopB32(value) => value.unparse_tokens(tokens),
            Inst::MadHiloCcType(value) => value.unparse_tokens(tokens),
            Inst::MadModeType(value) => value.unparse_tokens(tokens),
            Inst::MadHiSatS32(value) => value.unparse_tokens(tokens),
            Inst::MadFtzSatF32(value) => value.unparse_tokens(tokens),
            Inst::MadRndFtzSatF32(value) => value.unparse_tokens(tokens),
            Inst::MadRndF64(value) => value.unparse_tokens(tokens),
            Inst::Mad24ModeType(value) => value.unparse_tokens(tokens),
            Inst::Mad24HiSatS32(value) => value.unparse_tokens(tokens),
            Inst::MadcHiloCcType(value) => value.unparse_tokens(tokens),
            Inst::MapaSpaceType(value) => value.unparse_tokens(tokens),
            Inst::MatchAnySyncType(value) => value.unparse_tokens(tokens),
            Inst::MatchAllSyncType(value) => value.unparse_tokens(tokens),
            Inst::MaxAtype(value) => value.unparse_tokens(tokens),
            Inst::MaxReluBtype(value) => value.unparse_tokens(tokens),
            Inst::MaxFtzNanXorsignAbsF32(value) => value.unparse_tokens(tokens),
            Inst::MaxFtzNanAbsF32(value) => value.unparse_tokens(tokens),
            Inst::MaxF64(value) => value.unparse_tokens(tokens),
            Inst::MaxFtzNanXorsignAbsF16(value) => value.unparse_tokens(tokens),
            Inst::MaxFtzNanXorsignAbsF16x2(value) => value.unparse_tokens(tokens),
            Inst::MaxNanXorsignAbsBf16(value) => value.unparse_tokens(tokens),
            Inst::MaxNanXorsignAbsBf16x2(value) => value.unparse_tokens(tokens),
            Inst::MbarrierArriveSemScopeStateB64(value) => value.unparse_tokens(tokens),
            Inst::MbarrierArriveSemScopeSharedClusterB64(value) => value.unparse_tokens(tokens),
            Inst::MbarrierArriveExpectTxSemScopeStateB64(value) => value.unparse_tokens(tokens),
            Inst::MbarrierArriveExpectTxSemScopeSharedClusterB64(value) => value.unparse_tokens(tokens),
            Inst::MbarrierArriveNocompleteReleaseCtaStateB64(value) => value.unparse_tokens(tokens),
            Inst::MbarrierArriveDropSemScopeStateB64(value) => value.unparse_tokens(tokens),
            Inst::MbarrierArriveDropSemScopeSharedClusterB64(value) => value.unparse_tokens(tokens),
            Inst::MbarrierArriveDropExpectTxStateSemScopeB64(value) => value.unparse_tokens(tokens),
            Inst::MbarrierArriveDropExpectTxSharedClusterSemScopeB64(value) => value.unparse_tokens(tokens),
            Inst::MbarrierArriveDropNocompleteReleaseCtaStateB64(value) => value.unparse_tokens(tokens),
            Inst::MbarrierCompleteTxSemScopeSpaceB64(value) => value.unparse_tokens(tokens),
            Inst::MbarrierExpectTxSemScopeSpaceB64(value) => value.unparse_tokens(tokens),
            Inst::MbarrierInitStateB64(value) => value.unparse_tokens(tokens),
            Inst::MbarrierInvalStateB64(value) => value.unparse_tokens(tokens),
            Inst::MbarrierPendingCountB64(value) => value.unparse_tokens(tokens),
            Inst::MbarrierTestWaitSemScopeStateB64(value) => value.unparse_tokens(tokens),
            Inst::MbarrierTestWaitParitySemScopeStateB64(value) => value.unparse_tokens(tokens),
            Inst::MbarrierTryWaitSemScopeStateB64(value) => value.unparse_tokens(tokens),
            Inst::MbarrierTryWaitParitySemScopeStateB64(value) => value.unparse_tokens(tokens),
            Inst::FenceSemScope(value) => value.unparse_tokens(tokens),
            Inst::FenceAcquireSyncRestrictSharedClusterCluster(value) => value.unparse_tokens(tokens),
            Inst::FenceReleaseSyncRestrictSharedCtaCluster(value) => value.unparse_tokens(tokens),
            Inst::FenceOpRestrictReleaseCluster(value) => value.unparse_tokens(tokens),
            Inst::FenceProxyProxykind(value) => value.unparse_tokens(tokens),
            Inst::FenceProxyToProxykindFromProxykindReleaseScope(value) => value.unparse_tokens(tokens),
            Inst::FenceProxyToProxykindFromProxykindAcquireScope(value) => value.unparse_tokens(tokens),
            Inst::FenceProxyAsyncGenericAcquireSyncRestrictSharedClusterCluster(value) => value.unparse_tokens(tokens),
            Inst::FenceProxyAsyncGenericReleaseSyncRestrictSharedCtaCluster(value) => value.unparse_tokens(tokens),
            Inst::MembarLevel(value) => value.unparse_tokens(tokens),
            Inst::MembarProxyProxykind(value) => value.unparse_tokens(tokens),
            Inst::MinAtype(value) => value.unparse_tokens(tokens),
            Inst::MinReluBtype(value) => value.unparse_tokens(tokens),
            Inst::MinFtzNanXorsignAbsF32(value) => value.unparse_tokens(tokens),
            Inst::MinFtzNanAbsF32(value) => value.unparse_tokens(tokens),
            Inst::MinF64(value) => value.unparse_tokens(tokens),
            Inst::MinFtzNanXorsignAbsF16(value) => value.unparse_tokens(tokens),
            Inst::MinFtzNanXorsignAbsF16x2(value) => value.unparse_tokens(tokens),
            Inst::MinNanXorsignAbsBf16(value) => value.unparse_tokens(tokens),
            Inst::MinNanXorsignAbsBf16x2(value) => value.unparse_tokens(tokens),
            Inst::MmaSpvariantSyncAlignedM16n8k16RowColDtypeF16F16Ctype(value) => value.unparse_tokens(tokens),
            Inst::MmaSpvariantSyncAlignedM16n8k32RowColDtypeF16F16Ctype(value) => value.unparse_tokens(tokens),
            Inst::MmaSpvariantSyncAlignedM16n8k16RowColF32Bf16Bf16F32(value) => value.unparse_tokens(tokens),
            Inst::MmaSpvariantSyncAlignedM16n8k32RowColF32Bf16Bf16F32(value) => value.unparse_tokens(tokens),
            Inst::MmaSpvariantSyncAlignedM16n8k8RowColF32Tf32Tf32F32(value) => value.unparse_tokens(tokens),
            Inst::MmaSpvariantSyncAlignedM16n8k16RowColF32Tf32Tf32F32(value) => value.unparse_tokens(tokens),
            Inst::MmaSpvariantSyncAlignedM16n8k64RowColF32F8typeF8typeF32(value) => value.unparse_tokens(tokens),
            Inst::MmaSpOrderedMetadataSyncAlignedM16n8k64RowColKindDtypeF8f6f4typeF8f6f4typeCtype(value) => value.unparse_tokens(tokens),
            Inst::MmaSpvariantSyncAlignedM16n8k128RowColKindBlockScaleScaleVecSizeF32E2m1E2m1F32Stype(value) => value.unparse_tokens(tokens),
            Inst::MmaSpvariantSyncAlignedM16n8k128RowColKindBlockScaleScaleVecSizeF32E2m1E2m1F32Stype1(value) => value.unparse_tokens(tokens),
            Inst::MmaSpvariantSyncAlignedM16n8k64RowColKindBlockScaleScaleVecSizeF32F8f6f4typeF8f6f4typeF32Stype(value) => value.unparse_tokens(tokens),
            Inst::MmaSpvariantSyncAlignedShapeRowColSatfiniteS32AtypeBtypeS32(value) => value.unparse_tokens(tokens),
            Inst::MmaSpvariantSyncAlignedShapeRowColSatfiniteS32AtypeBtypeS321(value) => value.unparse_tokens(tokens),
            Inst::MmaSyncAlignedM8n8k4AlayoutBlayoutDtypeF16F16Ctype(value) => value.unparse_tokens(tokens),
            Inst::MmaSyncAlignedM16n8k8RowColDtypeF16F16Ctype(value) => value.unparse_tokens(tokens),
            Inst::MmaSyncAlignedM16n8k16RowColDtypeF16F16Ctype(value) => value.unparse_tokens(tokens),
            Inst::MmaSyncAlignedM16n8k4RowColF32Tf32Tf32F32(value) => value.unparse_tokens(tokens),
            Inst::MmaSyncAlignedM16n8k8RowColF32AtypeBtypeF32(value) => value.unparse_tokens(tokens),
            Inst::MmaSyncAlignedM16n8k16RowColF32Bf16Bf16F32(value) => value.unparse_tokens(tokens),
            Inst::MmaSyncAlignedShapeRowColDtypeF8typeF8typeCtype(value) => value.unparse_tokens(tokens),
            Inst::MmaSyncAlignedM16n8k32RowColKindDtypeF8f6f4typeF8f6f4typeCtype(value) => value.unparse_tokens(tokens),
            Inst::MmaSyncAlignedM16n8k64RowColKindBlockScaleScaleVecSizeF32E2m1E2m1F32Stype(value) => value.unparse_tokens(tokens),
            Inst::MmaSyncAlignedM16n8k64RowColKindBlockScaleScaleVecSizeF32E2m1E2m1F32Stype1(value) => value.unparse_tokens(tokens),
            Inst::MmaSyncAlignedM16n8k32RowColKindBlockScaleScaleVecSizeF32F8f6f4typeF8f6f4typeF32Stype(value) => value.unparse_tokens(tokens),
            Inst::MmaSyncAlignedShapeRowColF64F64F64F64(value) => value.unparse_tokens(tokens),
            Inst::MmaSyncAlignedShapeRowColSatfiniteS32AtypeBtypeS32(value) => value.unparse_tokens(tokens),
            Inst::MmaSyncAlignedShapeRowColSatfiniteS32AtypeBtypeS321(value) => value.unparse_tokens(tokens),
            Inst::MmaSyncAlignedShapeRowColS32B1B1S32BitopPopc(value) => value.unparse_tokens(tokens),
            Inst::MovType(value) => value.unparse_tokens(tokens),
            Inst::MovU32(value) => value.unparse_tokens(tokens),
            Inst::MovU64(value) => value.unparse_tokens(tokens),
            Inst::MovU321(value) => value.unparse_tokens(tokens),
            Inst::MovU641(value) => value.unparse_tokens(tokens),
            Inst::MovType1(value) => value.unparse_tokens(tokens),
            Inst::MovmatrixSyncAlignedShapeTransType(value) => value.unparse_tokens(tokens),
            Inst::MulModeType(value) => value.unparse_tokens(tokens),
            Inst::MulRndFtzSatF32(value) => value.unparse_tokens(tokens),
            Inst::MulRndFtzF32x2(value) => value.unparse_tokens(tokens),
            Inst::MulRndF64(value) => value.unparse_tokens(tokens),
            Inst::MulRndFtzSatF16(value) => value.unparse_tokens(tokens),
            Inst::MulRndFtzSatF16x2(value) => value.unparse_tokens(tokens),
            Inst::MulRndBf16(value) => value.unparse_tokens(tokens),
            Inst::MulRndBf16x2(value) => value.unparse_tokens(tokens),
            Inst::Mul24ModeType(value) => value.unparse_tokens(tokens),
            Inst::MultimemLdReduceLdsemScopeSsOpType(value) => value.unparse_tokens(tokens),
            Inst::MultimemLdReduceWeakSsOpType(value) => value.unparse_tokens(tokens),
            Inst::MultimemStStsemScopeSsType(value) => value.unparse_tokens(tokens),
            Inst::MultimemStWeakSsType(value) => value.unparse_tokens(tokens),
            Inst::MultimemRedRedsemScopeSsOpType(value) => value.unparse_tokens(tokens),
            Inst::MultimemLdReduceLdsemScopeSsOpAccPrecVecType(value) => value.unparse_tokens(tokens),
            Inst::MultimemLdReduceWeakSsOpAccPrecVecType(value) => value.unparse_tokens(tokens),
            Inst::MultimemStStsemScopeSsVecType(value) => value.unparse_tokens(tokens),
            Inst::MultimemStWeakSsVecType(value) => value.unparse_tokens(tokens),
            Inst::MultimemRedRedsemScopeSsRedopVecRedtype(value) => value.unparse_tokens(tokens),
            Inst::NanosleepU32(value) => value.unparse_tokens(tokens),
            Inst::NegType(value) => value.unparse_tokens(tokens),
            Inst::NegFtzF32(value) => value.unparse_tokens(tokens),
            Inst::NegF64(value) => value.unparse_tokens(tokens),
            Inst::NegFtzF16(value) => value.unparse_tokens(tokens),
            Inst::NegFtzF16x2(value) => value.unparse_tokens(tokens),
            Inst::NegBf16(value) => value.unparse_tokens(tokens),
            Inst::NegBf16x2(value) => value.unparse_tokens(tokens),
            Inst::NotType(value) => value.unparse_tokens(tokens),
            Inst::OrType(value) => value.unparse_tokens(tokens),
            Inst::Pmevent(value) => value.unparse_tokens(tokens),
            Inst::PmeventMask(value) => value.unparse_tokens(tokens),
            Inst::PopcType(value) => value.unparse_tokens(tokens),
            Inst::PrefetchSpaceLevel(value) => value.unparse_tokens(tokens),
            Inst::PrefetchGlobalLevelEvictionPriority(value) => value.unparse_tokens(tokens),
            Inst::PrefetchuL1(value) => value.unparse_tokens(tokens),
            Inst::PrefetchTensormapSpaceTensormap(value) => value.unparse_tokens(tokens),
            Inst::PrmtB32Mode(value) => value.unparse_tokens(tokens),
            Inst::RcpApproxFtzF64(value) => value.unparse_tokens(tokens),
            Inst::RcpApproxFtzF32(value) => value.unparse_tokens(tokens),
            Inst::RcpRndFtzF32(value) => value.unparse_tokens(tokens),
            Inst::RcpRndF64(value) => value.unparse_tokens(tokens),
            Inst::RedAsyncSemScopeSsCompletionMechanismOpType(value) => value.unparse_tokens(tokens),
            Inst::RedAsyncSemScopeSsCompletionMechanismOpType1(value) => value.unparse_tokens(tokens),
            Inst::RedAsyncSemScopeSsCompletionMechanismOpType2(value) => value.unparse_tokens(tokens),
            Inst::RedAsyncSemScopeSsCompletionMechanismAddType(value) => value.unparse_tokens(tokens),
            Inst::RedAsyncMmioSemScopeSsAddType(value) => value.unparse_tokens(tokens),
            Inst::RedOpSpaceSemScopeLevelCacheHintType(value) => value.unparse_tokens(tokens),
            Inst::RedAddSpaceSemScopeNoftzLevelCacheHintF16(value) => value.unparse_tokens(tokens),
            Inst::RedAddSpaceSemScopeNoftzLevelCacheHintF16x2(value) => value.unparse_tokens(tokens),
            Inst::RedAddSpaceSemScopeNoftzLevelCacheHintBf16(value) => value.unparse_tokens(tokens),
            Inst::RedAddSpaceSemScopeNoftzLevelCacheHintBf16x2(value) => value.unparse_tokens(tokens),
            Inst::RedAddSpaceSemScopeLevelCacheHintVec32BitF32(value) => value.unparse_tokens(tokens),
            Inst::RedOpSpaceSemScopeNoftzLevelCacheHintVec16BitHalfWordType(value) => value.unparse_tokens(tokens),
            Inst::RedOpSpaceSemScopeNoftzLevelCacheHintVec32BitPackedType(value) => value.unparse_tokens(tokens),
            Inst::ReduxSyncOpType(value) => value.unparse_tokens(tokens),
            Inst::ReduxSyncOpB32(value) => value.unparse_tokens(tokens),
            Inst::ReduxSyncOpAbsNanF32(value) => value.unparse_tokens(tokens),
            Inst::RemType(value) => value.unparse_tokens(tokens),
            Inst::RetUni(value) => value.unparse_tokens(tokens),
            Inst::RsqrtApproxFtzF64(value) => value.unparse_tokens(tokens),
            Inst::RsqrtApproxFtzF32(value) => value.unparse_tokens(tokens),
            Inst::RsqrtApproxF64(value) => value.unparse_tokens(tokens),
            Inst::SadType(value) => value.unparse_tokens(tokens),
            Inst::SelpType(value) => value.unparse_tokens(tokens),
            Inst::SetCmpopFtzDtypeStype(value) => value.unparse_tokens(tokens),
            Inst::SetCmpopBoolopFtzDtypeStype(value) => value.unparse_tokens(tokens),
            Inst::SetCmpopFtzF16Stype(value) => value.unparse_tokens(tokens),
            Inst::SetCmpopBoolopFtzF16Stype(value) => value.unparse_tokens(tokens),
            Inst::SetCmpopBf16Stype(value) => value.unparse_tokens(tokens),
            Inst::SetCmpopBoolopBf16Stype(value) => value.unparse_tokens(tokens),
            Inst::SetCmpopFtzDtypeF16(value) => value.unparse_tokens(tokens),
            Inst::SetCmpopBoolopFtzDtypeF16(value) => value.unparse_tokens(tokens),
            Inst::SetCmpopDtypeBf16(value) => value.unparse_tokens(tokens),
            Inst::SetCmpopBoolopDtypeBf16(value) => value.unparse_tokens(tokens),
            Inst::SetCmpopFtzDtypeF16x2(value) => value.unparse_tokens(tokens),
            Inst::SetCmpopBoolopFtzDtypeF16x2(value) => value.unparse_tokens(tokens),
            Inst::SetCmpopDtypeBf16x2(value) => value.unparse_tokens(tokens),
            Inst::SetCmpopBoolopDtypeBf16x2(value) => value.unparse_tokens(tokens),
            Inst::SetmaxnregActionSyncAlignedU32(value) => value.unparse_tokens(tokens),
            Inst::SetpCmpopFtzType(value) => value.unparse_tokens(tokens),
            Inst::SetpCmpopBoolopFtzType(value) => value.unparse_tokens(tokens),
            Inst::SetpCmpopFtzF16(value) => value.unparse_tokens(tokens),
            Inst::SetpCmpopBoolopFtzF16(value) => value.unparse_tokens(tokens),
            Inst::SetpCmpopFtzF16x2(value) => value.unparse_tokens(tokens),
            Inst::SetpCmpopBoolopFtzF16x2(value) => value.unparse_tokens(tokens),
            Inst::SetpCmpopBf16(value) => value.unparse_tokens(tokens),
            Inst::SetpCmpopBoolopBf16(value) => value.unparse_tokens(tokens),
            Inst::SetpCmpopBf16x2(value) => value.unparse_tokens(tokens),
            Inst::SetpCmpopBoolopBf16x2(value) => value.unparse_tokens(tokens),
            Inst::ShfLModeB32(value) => value.unparse_tokens(tokens),
            Inst::ShfRModeB32(value) => value.unparse_tokens(tokens),
            Inst::ShflSyncModeB32(value) => value.unparse_tokens(tokens),
            Inst::ShflModeB32(value) => value.unparse_tokens(tokens),
            Inst::ShlType(value) => value.unparse_tokens(tokens),
            Inst::ShrType(value) => value.unparse_tokens(tokens),
            Inst::SinApproxFtzF32(value) => value.unparse_tokens(tokens),
            Inst::SlctDtypeS32(value) => value.unparse_tokens(tokens),
            Inst::SlctFtzDtypeF32(value) => value.unparse_tokens(tokens),
            Inst::SqrtApproxFtzF32(value) => value.unparse_tokens(tokens),
            Inst::SqrtRndFtzF32(value) => value.unparse_tokens(tokens),
            Inst::SqrtRndF64(value) => value.unparse_tokens(tokens),
            Inst::StAsyncSemScopeSsCompletionMechanismVecType(value) => value.unparse_tokens(tokens),
            Inst::StAsyncMmioSemScopeSsType(value) => value.unparse_tokens(tokens),
            Inst::StBulkWeakSharedCta(value) => value.unparse_tokens(tokens),
            Inst::StWeakSsCopLevelCacheHintVecType(value) => value.unparse_tokens(tokens),
            Inst::StWeakSsLevel1EvictionPriorityLevel2EvictionPriorityLevelCacheHintVecType(value) => value.unparse_tokens(tokens),
            Inst::StVolatileSsVecType(value) => value.unparse_tokens(tokens),
            Inst::StRelaxedScopeSsLevel1EvictionPriorityLevel2EvictionPriorityLevelCacheHintVecType(value) => value.unparse_tokens(tokens),
            Inst::StReleaseScopeSsLevel1EvictionPriorityLevel2EvictionPriorityLevelCacheHintVecType(value) => value.unparse_tokens(tokens),
            Inst::StMmioRelaxedSysGlobalType(value) => value.unparse_tokens(tokens),
            Inst::StackrestoreType(value) => value.unparse_tokens(tokens),
            Inst::StacksaveType(value) => value.unparse_tokens(tokens),
            Inst::StmatrixSyncAlignedShapeNumTransSsType(value) => value.unparse_tokens(tokens),
            Inst::SubCcType(value) => value.unparse_tokens(tokens),
            Inst::SubType(value) => value.unparse_tokens(tokens),
            Inst::SubSatS32(value) => value.unparse_tokens(tokens),
            Inst::SubRndFtzSatF32(value) => value.unparse_tokens(tokens),
            Inst::SubRndFtzF32x2(value) => value.unparse_tokens(tokens),
            Inst::SubRndF64(value) => value.unparse_tokens(tokens),
            Inst::SubRndFtzSatF16(value) => value.unparse_tokens(tokens),
            Inst::SubRndFtzSatF16x2(value) => value.unparse_tokens(tokens),
            Inst::SubRndBf16(value) => value.unparse_tokens(tokens),
            Inst::SubRndBf16x2(value) => value.unparse_tokens(tokens),
            Inst::SubRndSatF32Atype(value) => value.unparse_tokens(tokens),
            Inst::SubcCcType(value) => value.unparse_tokens(tokens),
            Inst::SuldBGeomCopVecDtypeMode(value) => value.unparse_tokens(tokens),
            Inst::SuqQueryB32(value) => value.unparse_tokens(tokens),
            Inst::SuredBOpGeomCtypeMode(value) => value.unparse_tokens(tokens),
            Inst::SuredPOpGeomCtypeMode(value) => value.unparse_tokens(tokens),
            Inst::SustBDimCopVecCtypeMode(value) => value.unparse_tokens(tokens),
            Inst::SustPDimVecB32Mode(value) => value.unparse_tokens(tokens),
            Inst::SustBAdimCopVecCtypeMode(value) => value.unparse_tokens(tokens),
            Inst::SzextModeType(value) => value.unparse_tokens(tokens),
            Inst::TanhApproxType(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05AllocCtaGroupSyncAlignedSharedCtaB32(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05DeallocCtaGroupSyncAlignedB32(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05RelinquishAllocPermitCtaGroupSyncAligned(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05CommitCtaGroupCompletionMechanismSharedClusterMulticastB64(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05CpCtaGroupShapeMulticastDstSrcFmt(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05FenceBeforeThreadSync(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05FenceAfterThreadSync(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05LdSyncAlignedShape1NumPackB32(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05LdSyncAlignedShape2NumPackB32(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05LdRedSyncAlignedShape3NumRedopAbsNanF32(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05LdRedSyncAlignedShape4NumRedopAbsNanF32(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05LdRedSyncAlignedShape3NumRedopType(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05LdRedSyncAlignedShape4NumRedopType(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaSpCtaGroupKind(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaSpCtaGroupKind1(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaSpCtaGroupKindBlockScaleScaleVectorsize(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaSpCtaGroupKindBlockScaleScaleVectorsize1(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaSpCtaGroupKindCollectorUsage(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaSpCtaGroupKindAshiftCollectorUsage(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaSpCtaGroupKindAshiftCollectorUsage1(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaSpCtaGroupKindBlockScaleScaleVectorsizeCollectorUsage(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaSpCtaGroupKindBlockScaleScaleVectorsizeCollectorUsage1(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaSpCtaGroupKindI8(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaSpCtaGroupKindI81(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaSpCtaGroupKindI8CollectorUsage(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaSpCtaGroupKindI8AshiftCollectorUsage(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaSpCtaGroupKindI8AshiftCollectorUsage1(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaCtaGroupKind(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaCtaGroupKind1(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaCtaGroupKindBlockScaleScaleVectorsize(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaCtaGroupKindBlockScaleScaleVectorsize1(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaCtaGroupKindCollectorUsage(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaCtaGroupKindAshiftCollectorUsage(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaCtaGroupKindAshiftCollectorUsage1(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaCtaGroupKindBlockScaleScaleVectorsizeCollectorUsage(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaCtaGroupKindBlockScaleScaleVectorsizeCollectorUsage1(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaCtaGroupKindI8(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaCtaGroupKindI81(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaCtaGroupKindI8CollectorUsage(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaCtaGroupKindI8AshiftCollectorUsage(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaCtaGroupKindI8AshiftCollectorUsage1(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaWsSpCtaGroup1KindCollectorUsage(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaWsSpCtaGroup1KindCollectorUsage1(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaWsSpCtaGroup1KindI8CollectorUsage(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaWsSpCtaGroup1KindI8CollectorUsage1(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaWsCtaGroup1KindCollectorUsage(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaWsCtaGroup1KindCollectorUsage1(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaWsCtaGroup1KindI8CollectorUsage(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05MmaWsCtaGroup1KindI8CollectorUsage1(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05ShiftCtaGroupDown(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05StSyncAlignedShape1NumUnpackB32(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05StSyncAlignedShape2NumUnpackB32(value) => value.unparse_tokens(tokens),
            Inst::Tcgen05WaitOperationSyncAligned(value) => value.unparse_tokens(tokens),
            Inst::TensormapCpFenceproxyCpQualifiersFenceQualifiersSyncAligned(value) => value.unparse_tokens(tokens),
            Inst::TensormapReplaceModeField1SsB1024Type(value) => value.unparse_tokens(tokens),
            Inst::TensormapReplaceModeField2SsB1024Type(value) => value.unparse_tokens(tokens),
            Inst::TensormapReplaceModeField3SsB1024Type(value) => value.unparse_tokens(tokens),
            Inst::TestpOpType(value) => value.unparse_tokens(tokens),
            Inst::TexGeomV4DtypeCtype(value) => value.unparse_tokens(tokens),
            Inst::TexGeomV4DtypeCtype1(value) => value.unparse_tokens(tokens),
            Inst::TexGeomV2F16x2Ctype(value) => value.unparse_tokens(tokens),
            Inst::TexGeomV2F16x2Ctype1(value) => value.unparse_tokens(tokens),
            Inst::TexBaseGeomV4DtypeCtype(value) => value.unparse_tokens(tokens),
            Inst::TexLevelGeomV4DtypeCtype(value) => value.unparse_tokens(tokens),
            Inst::TexGradGeomV4DtypeCtype(value) => value.unparse_tokens(tokens),
            Inst::TexBaseGeomV2F16x2Ctype(value) => value.unparse_tokens(tokens),
            Inst::TexLevelGeomV2F16x2Ctype(value) => value.unparse_tokens(tokens),
            Inst::TexGradGeomV2F16x2Ctype(value) => value.unparse_tokens(tokens),
            Inst::Tld4Comp2dV4DtypeF32(value) => value.unparse_tokens(tokens),
            Inst::Tld4CompGeomV4DtypeF32(value) => value.unparse_tokens(tokens),
            Inst::Trap(value) => value.unparse_tokens(tokens),
            Inst::TxqTqueryB32(value) => value.unparse_tokens(tokens),
            Inst::TxqLevelTlqueryB32(value) => value.unparse_tokens(tokens),
            Inst::TxqSqueryB32(value) => value.unparse_tokens(tokens),
            Inst::VmadDtypeAtypeBtypeSatScale(value) => value.unparse_tokens(tokens),
            Inst::VmadDtypeAtypeBtypePoSatScale(value) => value.unparse_tokens(tokens),
            Inst::VaddDtypeAtypeBtypeSat(value) => value.unparse_tokens(tokens),
            Inst::VsubDtypeAtypeBtypeSat(value) => value.unparse_tokens(tokens),
            Inst::VabsdiffDtypeAtypeBtypeSat(value) => value.unparse_tokens(tokens),
            Inst::VminDtypeAtypeBtypeSat(value) => value.unparse_tokens(tokens),
            Inst::VmaxDtypeAtypeBtypeSat(value) => value.unparse_tokens(tokens),
            Inst::VaddDtypeAtypeBtypeSatOp2(value) => value.unparse_tokens(tokens),
            Inst::VsubDtypeAtypeBtypeSatOp2(value) => value.unparse_tokens(tokens),
            Inst::VabsdiffDtypeAtypeBtypeSatOp2(value) => value.unparse_tokens(tokens),
            Inst::VminDtypeAtypeBtypeSatOp2(value) => value.unparse_tokens(tokens),
            Inst::VmaxDtypeAtypeBtypeSatOp2(value) => value.unparse_tokens(tokens),
            Inst::VaddDtypeAtypeBtypeSat1(value) => value.unparse_tokens(tokens),
            Inst::VsubDtypeAtypeBtypeSat1(value) => value.unparse_tokens(tokens),
            Inst::VabsdiffDtypeAtypeBtypeSat1(value) => value.unparse_tokens(tokens),
            Inst::VminDtypeAtypeBtypeSat1(value) => value.unparse_tokens(tokens),
            Inst::VmaxDtypeAtypeBtypeSat1(value) => value.unparse_tokens(tokens),
            Inst::Vadd2DtypeAtypeBtypeSat(value) => value.unparse_tokens(tokens),
            Inst::Vsub2DtypeAtypeBtypeSat(value) => value.unparse_tokens(tokens),
            Inst::Vavrg2DtypeAtypeBtypeSat(value) => value.unparse_tokens(tokens),
            Inst::Vabsdiff2DtypeAtypeBtypeSat(value) => value.unparse_tokens(tokens),
            Inst::Vmin2DtypeAtypeBtypeSat(value) => value.unparse_tokens(tokens),
            Inst::Vmax2DtypeAtypeBtypeSat(value) => value.unparse_tokens(tokens),
            Inst::Vadd2DtypeAtypeBtypeAdd(value) => value.unparse_tokens(tokens),
            Inst::Vsub2DtypeAtypeBtypeAdd(value) => value.unparse_tokens(tokens),
            Inst::Vavrg2DtypeAtypeBtypeAdd(value) => value.unparse_tokens(tokens),
            Inst::Vabsdiff2DtypeAtypeBtypeAdd(value) => value.unparse_tokens(tokens),
            Inst::Vmin2DtypeAtypeBtypeAdd(value) => value.unparse_tokens(tokens),
            Inst::Vmax2DtypeAtypeBtypeAdd(value) => value.unparse_tokens(tokens),
            Inst::Vadd4DtypeAtypeBtypeSat(value) => value.unparse_tokens(tokens),
            Inst::Vsub4DtypeAtypeBtypeSat(value) => value.unparse_tokens(tokens),
            Inst::Vavrg4DtypeAtypeBtypeSat(value) => value.unparse_tokens(tokens),
            Inst::Vabsdiff4DtypeAtypeBtypeSat(value) => value.unparse_tokens(tokens),
            Inst::Vmin4DtypeAtypeBtypeSat(value) => value.unparse_tokens(tokens),
            Inst::Vmax4DtypeAtypeBtypeSat(value) => value.unparse_tokens(tokens),
            Inst::Vadd4DtypeAtypeBtypeAdd(value) => value.unparse_tokens(tokens),
            Inst::Vsub4DtypeAtypeBtypeAdd(value) => value.unparse_tokens(tokens),
            Inst::Vavrg4DtypeAtypeBtypeAdd(value) => value.unparse_tokens(tokens),
            Inst::Vabsdiff4DtypeAtypeBtypeAdd(value) => value.unparse_tokens(tokens),
            Inst::Vmin4DtypeAtypeBtypeAdd(value) => value.unparse_tokens(tokens),
            Inst::Vmax4DtypeAtypeBtypeAdd(value) => value.unparse_tokens(tokens),
            Inst::VoteSyncModePred(value) => value.unparse_tokens(tokens),
            Inst::VoteSyncBallotB32(value) => value.unparse_tokens(tokens),
            Inst::VoteModePred(value) => value.unparse_tokens(tokens),
            Inst::VoteBallotB32(value) => value.unparse_tokens(tokens),
            Inst::VsetAtypeBtypeCmp(value) => value.unparse_tokens(tokens),
            Inst::VsetAtypeBtypeCmpOp2(value) => value.unparse_tokens(tokens),
            Inst::VsetAtypeBtypeCmp1(value) => value.unparse_tokens(tokens),
            Inst::Vset2AtypeBtypeCmp(value) => value.unparse_tokens(tokens),
            Inst::Vset2AtypeBtypeCmpAdd(value) => value.unparse_tokens(tokens),
            Inst::Vset4AtypeBtypeCmp(value) => value.unparse_tokens(tokens),
            Inst::Vset4AtypeBtypeCmpAdd(value) => value.unparse_tokens(tokens),
            Inst::VshlDtypeAtypeU32SatMode(value) => value.unparse_tokens(tokens),
            Inst::VshrDtypeAtypeU32SatMode(value) => value.unparse_tokens(tokens),
            Inst::VshlDtypeAtypeU32SatModeOp2(value) => value.unparse_tokens(tokens),
            Inst::VshrDtypeAtypeU32SatModeOp2(value) => value.unparse_tokens(tokens),
            Inst::VshlDtypeAtypeU32SatMode1(value) => value.unparse_tokens(tokens),
            Inst::VshrDtypeAtypeU32SatMode1(value) => value.unparse_tokens(tokens),
            Inst::WgmmaCommitGroupSyncAligned(value) => value.unparse_tokens(tokens),
            Inst::WgmmaFenceSyncAligned(value) => value.unparse_tokens(tokens),
            Inst::WgmmaMmaAsyncSpSyncAlignedShapeDtypeF16F16(value) => value.unparse_tokens(tokens),
            Inst::WgmmaMmaAsyncSpSyncAlignedShapeDtypeF16F161(value) => value.unparse_tokens(tokens),
            Inst::WgmmaMmaAsyncSpSyncAlignedShapeDtypeBf16Bf16(value) => value.unparse_tokens(tokens),
            Inst::WgmmaMmaAsyncSpSyncAlignedShapeDtypeBf16Bf161(value) => value.unparse_tokens(tokens),
            Inst::WgmmaMmaAsyncSpSyncAlignedShapeDtypeTf32Tf32(value) => value.unparse_tokens(tokens),
            Inst::WgmmaMmaAsyncSpSyncAlignedShapeDtypeTf32Tf321(value) => value.unparse_tokens(tokens),
            Inst::WgmmaMmaAsyncSpSyncAlignedShapeDtypeAtypeBtype(value) => value.unparse_tokens(tokens),
            Inst::WgmmaMmaAsyncSpSyncAlignedShapeDtypeAtypeBtype1(value) => value.unparse_tokens(tokens),
            Inst::WgmmaMmaAsyncSpSyncAlignedShapeSatfiniteS32AtypeBtype(value) => value.unparse_tokens(tokens),
            Inst::WgmmaMmaAsyncSpSyncAlignedShapeSatfiniteS32AtypeBtype1(value) => value.unparse_tokens(tokens),
            Inst::WgmmaMmaAsyncSyncAlignedShapeDtypeF16F16(value) => value.unparse_tokens(tokens),
            Inst::WgmmaMmaAsyncSyncAlignedShapeDtypeF16F161(value) => value.unparse_tokens(tokens),
            Inst::WgmmaMmaAsyncSyncAlignedShapeDtypeBf16Bf16(value) => value.unparse_tokens(tokens),
            Inst::WgmmaMmaAsyncSyncAlignedShapeDtypeBf16Bf161(value) => value.unparse_tokens(tokens),
            Inst::WgmmaMmaAsyncSyncAlignedShapeDtypeTf32Tf32(value) => value.unparse_tokens(tokens),
            Inst::WgmmaMmaAsyncSyncAlignedShapeDtypeTf32Tf321(value) => value.unparse_tokens(tokens),
            Inst::WgmmaMmaAsyncSyncAlignedShapeDtypeAtypeBtype(value) => value.unparse_tokens(tokens),
            Inst::WgmmaMmaAsyncSyncAlignedShapeDtypeAtypeBtype1(value) => value.unparse_tokens(tokens),
            Inst::WgmmaMmaAsyncSyncAlignedShapeSatfiniteS32AtypeBtype(value) => value.unparse_tokens(tokens),
            Inst::WgmmaMmaAsyncSyncAlignedShapeSatfiniteS32AtypeBtype1(value) => value.unparse_tokens(tokens),
            Inst::WgmmaMmaAsyncSyncAlignedShapeS32B1B1OpPopc(value) => value.unparse_tokens(tokens),
            Inst::WgmmaMmaAsyncSyncAlignedShapeS32B1B1OpPopc1(value) => value.unparse_tokens(tokens),
            Inst::WgmmaWaitGroupSyncAligned(value) => value.unparse_tokens(tokens),
            Inst::WmmaLoadASyncAlignedLayoutShapeSsAtype(value) => value.unparse_tokens(tokens),
            Inst::WmmaLoadBSyncAlignedLayoutShapeSsBtype(value) => value.unparse_tokens(tokens),
            Inst::WmmaLoadCSyncAlignedLayoutShapeSsCtype(value) => value.unparse_tokens(tokens),
            Inst::WmmaLoadASyncAlignedLayoutShapeSsAtype1(value) => value.unparse_tokens(tokens),
            Inst::WmmaLoadBSyncAlignedLayoutShapeSsBtype1(value) => value.unparse_tokens(tokens),
            Inst::WmmaLoadCSyncAlignedLayoutShapeSsCtype1(value) => value.unparse_tokens(tokens),
            Inst::WmmaLoadASyncAlignedLayoutShapeSsAtype2(value) => value.unparse_tokens(tokens),
            Inst::WmmaLoadBSyncAlignedLayoutShapeSsBtype2(value) => value.unparse_tokens(tokens),
            Inst::WmmaLoadCSyncAlignedLayoutShapeSsCtype2(value) => value.unparse_tokens(tokens),
            Inst::WmmaLoadASyncAlignedLayoutShapeSsAtype3(value) => value.unparse_tokens(tokens),
            Inst::WmmaLoadBSyncAlignedLayoutShapeSsBtype3(value) => value.unparse_tokens(tokens),
            Inst::WmmaLoadCSyncAlignedLayoutShapeSsCtype3(value) => value.unparse_tokens(tokens),
            Inst::WmmaLoadASyncAlignedRowShapeSsAtype(value) => value.unparse_tokens(tokens),
            Inst::WmmaLoadBSyncAlignedColShapeSsBtype(value) => value.unparse_tokens(tokens),
            Inst::WmmaLoadCSyncAlignedLayoutShapeSsCtype4(value) => value.unparse_tokens(tokens),
            Inst::WmmaLoadASyncAlignedRowShapeSsAtype1(value) => value.unparse_tokens(tokens),
            Inst::WmmaLoadBSyncAlignedColShapeSsBtype1(value) => value.unparse_tokens(tokens),
            Inst::WmmaLoadCSyncAlignedLayoutShapeSsCtype5(value) => value.unparse_tokens(tokens),
            Inst::WmmaMmaSyncAlignedAlayoutBlayoutShapeDtypeCtype(value) => value.unparse_tokens(tokens),
            Inst::WmmaMmaSyncAlignedAlayoutBlayoutShapeS32AtypeBtypeS32Satfinite(value) => value.unparse_tokens(tokens),
            Inst::WmmaMmaSyncAlignedAlayoutBlayoutShapeF32AtypeBtypeF32(value) => value.unparse_tokens(tokens),
            Inst::WmmaMmaSyncAlignedAlayoutBlayoutShapeF32AtypeBtypeF321(value) => value.unparse_tokens(tokens),
            Inst::WmmaMmaSyncAlignedAlayoutBlayoutShapeRndF64F64F64F64(value) => value.unparse_tokens(tokens),
            Inst::WmmaMmaSyncAlignedRowColShapeS32AtypeBtypeS32Satfinite(value) => value.unparse_tokens(tokens),
            Inst::WmmaMmaOpPopcSyncAlignedRowColShapeS32AtypeBtypeS32(value) => value.unparse_tokens(tokens),
            Inst::WmmaStoreDSyncAlignedLayoutShapeSsType(value) => value.unparse_tokens(tokens),
            Inst::WmmaStoreDSyncAlignedLayoutShapeSsType1(value) => value.unparse_tokens(tokens),
            Inst::WmmaStoreDSyncAlignedLayoutShapeSsType2(value) => value.unparse_tokens(tokens),
            Inst::WmmaStoreDSyncAlignedLayoutShapeSsType3(value) => value.unparse_tokens(tokens),
            Inst::XorType(value) => value.unparse_tokens(tokens),
        }
    }
}
